/**
 * Copyright (c) 2026 hangtiancheng
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import z from "zod";

/**
 * Metadata for a single team member. isActive uses an optional field to preserve
 * three-state semantics: absent means just registered and not yet started,
 * true means actively running, false means idle.
 */
export const TeamMemberEntrySchema = z.object({
  agentId: z.string(),
  name: z.string(),
  agentType: z.string().optional(),
  model: z.string().optional(),
  joinedAt: z.number(),
  worktreePath: z.string().optional(),
  backendType: z.string().optional(),
  isActive: z.boolean().optional(),
});

export type TeamMemberEntry = z.infer<typeof TeamMemberEntrySchema>;

/**
 * On-disk representation of team configuration, stored at <teamsBaseDir>/<slug>/config.json.
 *
 * The in-memory Member carries a mailbox, cancel callback, and conversation — none of
 * which can be serialized — so what gets persisted is this pure-metadata structure,
 * with both sides correlated by member name.
 *
 * This file addresses cross-process and cross-restart continuity: pane teammates are
 * independent processes that need to know which team they belong to and who their
 * peers are after startup; users restarting Yukino must be able to resume prior teams.
 */
const TeamFileSchema = z.object({
  name: z.string(),
  description: z.string().optional(),
  createdAt: z.number(),
  leadAgentId: z.string(),
  members: z.array(TeamMemberEntrySchema),
});

export type TeamFile = z.infer<typeof TeamFileSchema>;

/**
 * Root directory for all team data. Placed under the user's home directory rather than
 * the project directory because pane teammates are independent processes whose working
 * directory may be swapped by a worktree; using the home directory guarantees both the
 * teammate process and the Lead locate the same team configuration.
 */
export function teamsBaseDir(): string {
  return join(homedir(), ".yukino", "teams");
}

/**
 * Compresses a team name into a valid directory name: all non-alphanumeric characters
 * are replaced with hyphens and the result is lowercased. Team names are generated by
 * the LLM and may contain spaces, CJK characters, or punctuation — without sanitization
 * they would cause filesystem issues across platforms.
 */
export function sanitizeTeamName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase();
}

export function teamDir(name: string): string {
  return join(teamsBaseDir(), sanitizeTeamName(name));
}

/**
 * Lists every team that has data on disk, keyed by the (already sanitized)
 * team directory name. Returns an empty list when the base dir does not exist.
 * Used to sweep residual teams left behind by previous sessions.
 */
export function listTeamNames(): string[] {
  try {
    return readdirSync(teamsBaseDir(), { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name);
  } catch {
    return [];
  }
}

export function teamConfigPath(name: string): string {
  return join(teamDir(name), "config.json");
}

/**
 * Reads team configuration. Returns null when the file does not exist, allowing the
 * caller to treat it as "team not found" rather than propagating an exception.
 */
export function readTeamFile(name: string): TeamFile | null {
  const path = teamConfigPath(name);
  if (!existsSync(path)) {
    return null;
  }
  try {
    const raw: unknown = JSON.parse(readFileSync(path, "utf-8"));
    return TeamFileSchema.parse(raw);
  } catch {
    return null;
  }
}

/**
 * Writes team configuration, creating the directory if it does not exist. A write
 * failure only invalidates cross-process and cross-restart state — the in-memory team
 * continues to function — so errors are swallowed here.
 */
export function writeTeamFile(name: string, file: TeamFile): void {
  try {
    const path = teamConfigPath(name);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, JSON.stringify(file, null, 2), "utf-8");
  } catch {
    // best-effort
  }
}
